### ISSUE TITLE
Create an infographic to illustrate how the product works

### ISSUE THREAD

**Issue by nienn** [readthedocs/site-community#115]
Create an infographic to help explain the product, its features and complexities.

* Initial concept brainstormed during the initial UX study and mockup here: https://github.com/readthedocs/site-community/pull/3#issuecomment-979422097

Proposed work:
- [ ] Brainstorm the infographic concept and guidelines.
- [ ] Create the infographic.
- [ ] Add the infographic to the Product page.
- [ ] Consider creating additional graphics and infographics to add to this and to other pages to help clarifying features and concepts.

**Comment by agjohnson** [comment]
I used screenshots on the about page to capture some of this. I think this is good enough for now and is more maintainable going forward.
