### ISSUE TITLE
Add page for choosing platform to start on

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#128]
Perhaps it makes sense to combine two changes we've discussed into a single page here:

- Make sign up UX more obvious for commercial users -- "Start a new trial for your company!" instead of "Sign up!"
- And guide user to the correct platform, community/commercial, with some additional copy.

I could sketch out how this page might look, but I'm not sure if it's best to include here or not. Likely, we'll want to do some form things that are better served with Django?

This page might be the beginning of a login/sign up page that supports two platforms, and we do some fancier API calls and JS to manage the log in process.

Work:

- [x] Make "Get started" and sign up links open a modal with the selection
- [x] Make "Open application" button dropdown a list

**Comment by humitos** [comment]
I just wanted to link the issue where we talked about a lot about things related to this: https://github.com/readthedocs/readthedocs-corporate/issues/1407 in case it could be useful in the future when we come back to this particular task.

**Comment by agjohnson** [comment]
Yeah indeed there is overlap with that issue. I want to try out a few options here before raising this as a replacement for an application page, I'm not entirely sure which would be best short term or long term

**Comment by agjohnson** [comment]
I ended up implementing this yesterday as a modal on the homepage:

![image](https://user-images.githubusercontent.com/1140183/179806919-be8cdf1f-c254-4e10-b985-54bd235b3cdb.png)

![image](https://user-images.githubusercontent.com/1140183/179806948-ee601b0e-b825-445b-9bf4-5eeee61b0ee1.png)

It needs tweaked a little bit, and probably some room for A/B testing there in the future -- swapping plan order, making business plans prominent, more pricing information, etc.

**Comment by agjohnson** [comment]
Also, note, this does not address linking to two separate *log in* pages. That probably should be a less content heavy option -- a dropdown for now, but automatic in the future? This is a bigger discussion

**Comment by ericholscher** [comment]
I like the signup breakdown. Puts the choice right up front, which is great.

**Comment by agjohnson** [comment]
I added a basic log in dropdown for now:

![image](https://user-images.githubusercontent.com/1140183/179917136-a8029c00-32ae-444c-9ef9-ba03df9bcea1.png)

![image](https://user-images.githubusercontent.com/1140183/179917212-21b7865e-e803-46b9-8554-74d7b0df44c6.png)
