### ISSUE TITLE
Pattern for JS routing

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#15]
One piece we might want to figure out is an easy way to manage routing in JS. Avoiding inline scripts is a benefit to our application, so perhaps makes sense to also utilize the same patterns on all of our properties. It is less of an issue when everything is 1) static files and 2) under our control though.

It would be great if we could align this and the application templates. Currently, the application templates use knockout, and some amount of knockout to initialize the JS view we're using in the page. This does require the application template JS to register all of the views, and uses some element attributes to initialize the view.

For example, a template might have:

```html
<div class="ui segment" data-bind="using: BuildListView()">
```

Example:
https://github.com/readthedocs/ext-theme/blob/master/readthedocsext/theme/templates/builds/build_detail.html#L16

This is used to initialize the knockout view used by the template. It's not awful, but isn't great either. I could see us skipping any fancy URL based routing and just continuing this pattern here, to keep things algined.

Any other good options for routing requests to a view in JS? There are dedicated libraries I know of, but most either focus on push state and/or full URL routing. This was skipped on our application templates because we already define URL->view in Django, duplicating URL->view in JS didn't seem right. It seemed like our templates should dictate the JS view that is used.

**Comment by nienn** [comment]
> This was skipped on our application templates because we already define URL->view in Django, duplicating URL->view in JS didn't seem right.

Seems easier to continue the same pattern, but I'm not yet familiar with the code logic of the application so I might be missing something. Is there any reason that we'd want JS to dictate the views on the landing pages? Are we aiming for a SPA?

I could see a SPA pattern being more useful on the application side, where there's more dynamic data and no SEO concerns, but there Django is already managing the views. Are there any benefits - or requisites - of changing the pattern for the landing pages where there's mostly static contents?

**Comment by agjohnson** [comment]
This isn't looking important after all, it's looking like we won't have much custom JS to manage anyways.
