### ISSUE TITLE
Build custom house ads pointing at our new website landing pages, and track results

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/site-community#153]
The goal here is to have a new landing page on the site-community, and start sending traffic to it to measure engagement. We can do this ahead of fully launching the landing pages as the frontpage of the site, to test out some of our marketing messages. 

Thinking this will be a **Sphinx & Python** landing page, and have it target Python-language docs as a house ad.

**Comment by ericholscher** [comment]
The house ad is shipped! It's currently pointed at the front page, since the landing page isn't quite ready for prime time yet. 

Still a bit day though 🎉

**Comment by ericholscher** [comment]
This is now shipped in https://github.com/readthedocs/site-community/pull/152, but we haven't shipped a house ad for it yet.

@agjohnson I'd love it if you had time to throw together a good ad image while you're engaged with this.

**Comment by agjohnson** [comment]
I'll put this on my list for after meetings tomorrow

**Comment by ericholscher** [comment]
I've shipped a new ad pointing at our Sphinx landing page: https://server.ethicalads.io/advertiser/readthedocs/flights/house-ads-rtd-house-2022/advertisements/rtd-for-business-copy-copy-copy-copy-copy/

![Screenshot 2022-11-10 at 2 34 22 PM](https://user-images.githubusercontent.com/25510/201220375-0444081f-7e05-4c9a-9cb1-d6a042546e77.png)
