### ISSUE TITLE
Content: update pricing page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#158]
I have some structure changes and content changes here, but won't focus too much on this page. I have a branch already, but just tracking this on our roadmap.

Additionally:

- [x] Update pricing style and tune page information
- [x] Add feature detail list
- [x] Add enterprise call out to pricing page

**Comment by ericholscher** [comment]
Next steps: Link PR, and if it doesn't move this sprint, backlog it.

**Comment by agjohnson** [comment]
Actually, if I can't finish this up on my thurs/fri this week, lets try to merge what I have completed. I left this about 95% done, so shouldn't take much work.

**Comment by ericholscher** [comment]
Yea, as long as it's better than what we have, I'm 👍 on merging and iterating.

**Comment by humitos** [comment]
Do we have a PR for this?

**Comment by ericholscher** [comment]
I think @agjohnson has the code locally, but I'd love to get it shipped since this page is already getting traffic:

![Screenshot 2022-11-03 at 1 46 19 PM](https://user-images.githubusercontent.com/25510/199830634-94a2c575-41ba-4b01-9a9e-77f1f76f5799.png)

**Comment by ericholscher** [comment]
🎉
