### ISSUE TITLE
Header navigation should highlight working page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#37]
It's currently static, but should show `active` class on the selected tab. Example of something similar here:

https://github.com/readthedocs/ethicalads.io/blob/main/ethicalads-theme/templates/includes/navigation.html#L26-L32

Also probably worth seeing how existing Pelican themes do this in case the above implementation was specific to EA.

**Comment by nienn** [comment]
👍 this should be done as soon as I start iterating through the merged templates to add dynamic functionalities.
