### ISSUE TITLE
Add blog templates

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#38]
We'll need a template or two for blog content. There are maybe a few decisions lurking in this task, but let's plan to start small.

At very least, I know we'll come across whether or not we want to use image headers on every blog post. The answer here is similar to EA, and we probably do want to plan on blog posts have some graphical element at the top. Eventually, this is configurable and we have a stock of images to use at the top.

The immediate answer is: plan for an image eventually, but let's ship with just a colored background placeholder where we will use an image eventually.

EA has some helpful prior art here:
https://github.com/readthedocs/ethicalads.io/blob/main/ethicalads-theme/templates/article.html

**Comment by nienn** [comment]
We also need a template `index.html` for the blog home. Not sure if you meant to include that work here. I opened a separate PR to help making issues more actionable:
* #50
