### ISSUE TITLE
Automate body id

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#41]
I keep seeing the body id block:

```jinja
{% block body_id %}pricing{% endblock %}
```

I bet we can easily automate this using the page title lowercased, slugged, or something similar. This is pseudo-jinja, but:

```jinja
<body id="{{ page_title|lower }}">
```

**Comment by nienn** [comment]
This `id` is meant for `CSS` and `JS` usage.
Any changes can break the styles or scripts dependant on it. Do we want the ability to edit it that easily in an `.md` file?
Also, it would block changes to the page display title. Altering the title would be dependant on updating the `CSS` and `JS` rules as well.

Maybe we could add an explicit variable in the .md file, meant only for this, and/or related, usages:
```jinja
<body id="{{body_id}}">
```

**Comment by nienn** [comment]
I just found this variable that might make sense to use here:
```jinja
<body id="{{page_name}}">
```
_From the docs: https://docs.getpelican.com/en/latest/themes.html#index-html._

**Comment by agjohnson** [comment]
Yeah, `page_name` looks correct, though my point above about slugifying this variable still stand. I assume that variable has path separator and other characters not supported by the id attr.

I suppose I'm only discussing this change for the `page.html` template. For a blog post template, we shouldn't be writing custom CSS or arguably JS for an individual blog post. We probably still just want a generic id there, set by the template.

> Do we want the ability to edit it that easily in an .md file

I'd say no for now. If anything we'll have a custom blog post template, but really shouldn't have per-blog-post CSS or JS.

**Comment by nienn** [comment]
I'm not sure exactly how the slugify is implemented with python/pelican but, in principle, I'm +1 on it.

The discussion on the body `id` is only for the marketing pages, the blog posts should all use the same template `post.html`, where maybe there will be an `id` but it will be the same for all posts.

**Comment by agjohnson** [comment]
Note: after the topnav issue, I believe what we want is `{% if page %}{{ page.slug }}{% endif %}`

I pushed up an example at #45 

> blog posts should all use the same template post.html

Blog posts ("articles" in pelican nomenclature) don't use `page.html`, they will use `article.html`, so we can set a different body id there that doesn't use `page.slug`

**Comment by agjohnson** [comment]
I've found this can be removed entirely. The only thing we were using the body id for was custom CSS. Most of this CSS is already replaced with native SUI components instead, so per-page targeting has not been needed.
