### ISSUE TITLE
Graphics: finalize main graphic on front page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#42]
This is still a stock image, we'll need:

- [ ] To get a license for the art we're using
- [ ] Store the art sources somewhere
- [ ] Alter sources with the changes on the graphics now
- [ ] Optimize an output for usage here

This is a good fit for the images repo actually, but will track this here for now I suppose.

**Comment by nienn** [comment]
The original image is here: https://www.shutterstock.com/pt/image-vector/concept-user-manual-tutorial-people-exploring-1315141181

**Comment by agjohnson** [comment]
I was thinking about this graphic more today, and got some feedback, and I'm having more second thoughts on this graphic direction now.

I apparently have a number of thoughts here, but the main thing I'm left with is that I don't think it makes sense to have you spend time altering and polishing this artist's work, because we're not committed to using this artist's work as part of a congruent design and brand. And unfortunately, I don't feel we'll realistically be able to maintain enough momentum here to really build strong branding. The graphic feels like a generic fit because of this right now, and already introduces some design inconsistency with the graphics below.

I do have some thoughts here, but my main goal is to ease into branding and just to a lite version of branding. Anything else is going to be oversubscribing us I feel.

For now, let's pause on this graphic, unless you'd like to discuss some intermediate options. I'd like to iterate on this image already, and I don't want the homepage to go back to a design discussion at this point. It's probably easiest to skip the image for now and accept some additional spacing in header for the moment. My thoughts are to use a background cover repeatable pattern, mimicking the chunky, bold style of the graphics below. The main graphic would be easy to accomplish and would illustrate RTD in less abstract ways.

**Comment by nienn** [comment]
Sure, there will always be a better option. If you have an idea for a branding path that will allow more consistency throughout the site, then that's fine. But if the problem is lack of resources to maintain momentum will not simply removing the image move the landing page two steps back?

It's the only strong graphic element on this page and it can be changed at anytime in future, when there's a ready alternative. Removing it now and having to account for the lack of it is more work than making the small needed edits to the current image, once it's bought.

**Comment by agjohnson** [comment]
> But if the problem is lack of resources to maintain momentum will not simply removing the image move the landing page two steps back?

I think we have momentum to maintain much simpler branding. This artist's work does require much more design time to execute branding around however. None of the graphics are a great fit for us, and all require manipulation -- this one included.

I do want to emphasize design congruity. If we had more resources to continue manipulating this design style, we might make this artist's work fit our site. But right now it has a generic feel to it because it's not manipulated yet.

> I wouldn't remove it.

Just to clarify, the graphic now is *not* finished. I'm not describing removing a finished graphic, I'm describing not spending effort to produce an image that I see us changing in a short time frame.

This graphic is only a mockup, the image is watermarked/etc. We still need to alter the actual illustration, and go through some process to finalize the image. Likely hours to a day of cumulative work here. And this is a lot on a limited time frame.

I'm also saying that I think we can even just leave the mockup graphic for now, it doesn't even need to be removed. I'm describing using the same layout, structure, and element placement even. But instead of opinionated, abstract art, we'd use something that does balance the styles on that page more and is far easier to execute.
