### ISSUE TITLE
Footer: Improve sponsors styling

### ISSUE THREAD

**Issue by nienn** [readthedocs/site-community#53]
The sponsor logos look weird, too messy and could use some style adjustments.

Tree simple fixes could be:
 * Make them darker and in 1 single color
 * Make them a bit smaller. Instead of being placed inside the `. container` width they could use a `.row .column.twelve.width` to narrow the max with on large screens.
 * Adjust the text size and color of the  `.sub.header`

**Comment by agjohnson** [comment]
Covered in #124, but this might not be a great fit for the website, maybe more for the application and docs instead. I'll close this out, as it's not part of the homepage anymore.
