### ISSUE TITLE
Footer: change columns order

### ISSUE THREAD

**Issue by nienn** [readthedocs/site-community#55]
The graphic balance of the elements in the footer feel weird. The newsletter block is the one with more impact and is also the only one that fills the full width of its column. For these two reasons I think it works best for it to be on the rightmost side. There, being full width, will align more gracefully with the page structure, and it will also remove a blockage that is currently causing on the reading flow, by being too heavy on the beginning of the line.

The two other columns could benefit from being narrower, as they currently leave too much blank space after the short lines. This could be done either by dividing them in one extra column or by finding a better balance width the newsletter column.

**Comment by agjohnson** [comment]
I replaced a lot of the styling with native SUI elements. The footer currently looks fairly balanced on desktop:

![image](https://user-images.githubusercontent.com/1140183/179877587-32c290b1-f75e-4474-a308-a4a442885d8e.png)

This was done back on 06f33d48ff9f4787710c082eb7dd20d24c236049
