### ISSUE TITLE
Webpack not building images from the content folder

### ISSUE THREAD

**Issue by nienn** [readthedocs/site-community#73]
Webpack is not building the images from the `content` folder.

More precicely, `/content/images/` needs to be built into `/output/images/`.

Currently only images from `/readthedocs-theme/static/img/` are built into `/output/theme/img`

**Comment by agjohnson** [comment]
Where exactly are you noticing the missing images?

Webpack shouldn't be touching these files at all, webpack should only build the CSS/JS and related assets for the Pelican theme. That is, images that are directly referenced by CSS in the Pelican theme LESS source files.

The images in `content/images` or whatever path is configured for these images, are all handled by Pelican instead. There is configuration for the image include path, and these images should be copied to `output/` when `pelican content` is run.

**Comment by nienn** [comment]
Forgot about Pelican! Found the problem in `pelicanconf.py` who was not referencing the images path in `STATIC_PATHS`.
Thanks for the reminder.
* Summited a PR to fix it #74

I'm closing this issue since its unrelated.
