### ISSUE TITLE
Company page adjustments

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#79]
- [x] Juanlu is not on the core team anymore.
- [x] Uneven headers around "Our blog"
- [x] Brand guideline button seems like it might be better as a link, or with sentence case.

![image](https://user-images.githubusercontent.com/1140183/154216860-008698ef-aa0c-4b96-bde3-310b85ba809c.png)

![image](https://user-images.githubusercontent.com/1140183/154217061-7b4e0481-d749-4785-a12c-33cbaf3e9d75.png)

**Comment by nienn** [comment]
> - [ ]  Newsletter button seems like it might be better as a link, or with sentence case.

The newsletter column was purposely different from the other two.
Are you suggesting it should follow the same format as the previous two? ie: same header, same alignment and use a `link` in place of the `input` and `button`

**Comment by agjohnson** [comment]
I'm only discussing the brand guidelines button, not the section itself. It doesn't seem like it should be a button, but as a invert black button it really stands out and the lowercase looks wrong.

**Comment by nienn** [comment]
I'm still not sure what you have in mind for:

> - [ ] Newsletter button seems like it might be better as a link, or with sentence case.

and:

![Screenshot 2022-02-22 100630](https://user-images.githubusercontent.com/4049894/155110106-1fad8cdf-76c7-42e0-a1de-4cac0eeceb26.png)

<br>

Other than those two items, this issue might be closed with:
* #82

**Comment by agjohnson** [comment]
The subscribe header has several issues:

* The headings are uneven. There are two larger headings to the left and the newletter heading is both smaller and not vertically aligned with the others.
* It should be `Subscribe to our newletter`, there is a typo
* Casing should be sentence case

> I'm still not sure what you have in mind for

Sorry, this is referencing the brand guideline button.
