### ISSUE TITLE
Pricing page button links

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#80]
The pricing page buttons don't currently link to anything. All of the sign up buttons should link to the respective user sign up URLs. This can be altered to do something specific in the future, but for now we don't have this functionality in the UI. That is, you don't get to select your plan when you sign up for an account, it's all on the Trial plan.

**Comment by nienn** [comment]
We can still link to [**readthedocs.org/accounts/signup**](https://readthedocs.org/accounts/signup) vs [**readthedocs.com/accounts/signup**](https://readthedocs.com/accounts/signup) by either adding new info or by using the current buttons to link to those.
