### ISSUE TITLE
Homepage: replace hardcoded mock announcements

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/site-community#88]
The announcements section is hardcoded and will be very unlikely to get any updates if it isn't automated. This should probably be fed by blog content automatically. It might be wise to have some way to filter these blog posts, such as search for blog posts with a `frontpage: true` metadata or similar, but that can even be separate. We just need to ensure these can be current.

![image](https://user-images.githubusercontent.com/1140183/155446275-4cd9e8f2-ab10-456b-b04f-76c33e45c8bd.png)

## Work

- [ ] Decide if any of these blocks are better as static blocks -- do we want 3 blog articles up front?
- [ ] Replace the hardcoded elements with the same sort of logic from `articles.html`. Only show 3 most recent or most important blog posts
- [ ] If getting blog posts by metadata is difficult then let's skip this for now.

**Comment by nienn** [comment]
* Related issue: #62

**Comment by nienn** [comment]
* This was resolved together with #62 with #97.
